#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin.
# Build: compile src/ → lib/ with the dsh checkout's tsc.
# Requires DSH_CHECKOUT pointing at a dsh source checkout (auto-probe below).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# DSH_CHECKOUT 探测：环境变量 → 常见路径
CHECKOUT="${DSH_CHECKOUT:-}"
if [ -z "$CHECKOUT" ]; then
  for candidate in "$HOME/deepseek-harness" "$HOME/.dsh/deepseek-harness" "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness"; do
    if [ -d "$candidate/packages" ] || [ -d "$candidate/node_modules/@deepseek-ai" ]; then CHECKOUT="$candidate"; break; fi
  done
fi
if [ -z "$CHECKOUT" ] || { [ ! -d "$CHECKOUT/packages" ] && [ ! -d "$CHECKOUT/node_modules/@deepseek-ai" ]; }; then
  echo "build: cannot locate the dsh checkout (set DSH_CHECKOUT)" >&2
  exit 1
fi

TSC="${TSC:-$CHECKOUT/node_modules/.bin/tsc}"
if [ ! -x "$TSC" ] && [ ! -f "$TSC.cmd" ] && [ ! -f "$TSC" ]; then
  echo "build: tsc not found at $TSC" >&2
  exit 1
fi

link_pkg() {
  local target="$CHECKOUT/$2"
  if [ ! -e "$target" ]; then
    echo "build: dependency target missing: $target" >&2
    exit 1
  fi
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = path.resolve(process.argv[2]);
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "node_modules/$1" "$target"
}

echo "=== Linking build dependencies (checkout: $CHECKOUT) ==="
mkdir -p node_modules/@deepseek-ai
node -e "const fs=require('fs');fs.rmSync('node_modules/@standard-schema',{recursive:true,force:true})"
if [ -d "$CHECKOUT/packages" ]; then
  link_pkg cordis vendor/cordis
  link_pkg @deepseek-ai/cordis vendor/cordis
  link_pkg cosmokit vendor/cosmokit
  link_pkg schemastery vendor/schemastery
  link_pkg @deepseek-ai/dsh-tools packages/core/tools
  link_pkg @deepseek-ai/dsh-llm packages/llm/llm
  link_pkg @deepseek-ai/dsh-system-prompt packages/core/system-prompt
  link_pkg @deepseek-ai/dsh-settings packages/settings/settings
  link_pkg @deepseek-ai/dsh-credentials packages/credentials/credentials
  link_pkg @deepseek-ai/dsh-client-runtime packages/client/runtime
  link_pkg @deepseek-ai/dsh-client-ui-slots packages/client/ui-slots
  link_pkg react node_modules/react
else
  link_pkg cordis node_modules/@deepseek-ai/cordis
  link_pkg @deepseek-ai/cordis node_modules/@deepseek-ai/cordis
  link_pkg cosmokit node_modules/@deepseek-ai/cosmokit
  link_pkg schemastery node_modules/@deepseek-ai/schemastery
  link_pkg @deepseek-ai/dsh-tools node_modules/@deepseek-ai/dsh-tools
  link_pkg @deepseek-ai/dsh-llm node_modules/@deepseek-ai/dsh-llm
  link_pkg @deepseek-ai/dsh-system-prompt node_modules/@deepseek-ai/dsh-system-prompt
  link_pkg @deepseek-ai/dsh-settings node_modules/@deepseek-ai/dsh-settings
  link_pkg @deepseek-ai/dsh-credentials node_modules/@deepseek-ai/dsh-credentials
  link_pkg @deepseek-ai/dsh-client-runtime node_modules/@deepseek-ai/dsh-client-runtime
  link_pkg @deepseek-ai/dsh-client-ui-slots node_modules/@deepseek-ai/dsh-client-ui-slots
  link_pkg react node_modules/react
fi
# @types/node（编译类型；checkout 自带）
link_pkg @types/node node_modules/@types/node

STD_SCHEMA=$(find "$CHECKOUT/node_modules/.pnpm" -maxdepth 1 -type d -iname '@standard-schema+spec@*' 2>/dev/null | head -1 || true)
if [ -n "$STD_SCHEMA" ]; then
  node -e "
    const fs = require('fs');
    const path = require('path');
    fs.rmSync('node_modules/@standard-schema', { recursive: true, force: true });
    fs.mkdirSync('node_modules/@standard-schema', { recursive: true });
    fs.symlinkSync(path.resolve(process.argv[1]), path.resolve('node_modules/@standard-schema/spec'), process.platform === 'win32' ? 'junction' : 'dir');
  " "$STD_SCHEMA/node_modules/@standard-schema/spec"
elif [ -d "$CHECKOUT/node_modules/@standard-schema/spec" ]; then
  node -e "
    const fs = require('fs');
    const path = require('path');
    fs.rmSync('node_modules/@standard-schema', { recursive: true, force: true });
    fs.mkdirSync('node_modules/@standard-schema', { recursive: true });
    fs.symlinkSync(path.resolve(process.argv[1]), path.resolve('node_modules/@standard-schema/spec'), process.platform === 'win32' ? 'junction' : 'dir');
  " "$CHECKOUT/node_modules/@standard-schema/spec"
fi

echo "=== Compiling src → lib ==="
if [ -n "${TSC_RUNNER:-}" ]; then
  "$TSC_RUNNER" "$TSC" -p tsconfig.json
else
  "$TSC" -p tsconfig.json
fi

if [ -x "node_modules/.bin/tsdown" ] || [ -f "node_modules/.bin/tsdown.cmd" ]; then
  echo "=== Building client bundle ==="
  node node_modules/tsdown/dist/run.mjs
else
  echo "build: tsdown not installed; skipping client bundle (run: npm install --no-save --legacy-peer-deps tsdown@0.22.14)" >&2
fi
echo "=== Build complete ==="
